<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$quote = $objectManager->create('Magento\Checkout\Model\Cart')->getQuote();
$itemsCount = $quote->getItemsCount();
?>
<h1>Write Your Product comment here...</h1>
<form id="save" action="/comment/index/save" method="POST">
    <?php for ($i = 1; $i <= $itemsCount; $i++) : ?>
        <span>order comment for item <?php echo $i ?></span>
        <br>
        <input type="text" name="<?php echo "comment" . $i ?>" id="<?php echo "comment" . $i ?>" placeholder="order comment for item <?php echo $i ?> ...." style="width: 631px;height: 50px;">
        <br>
        <br>
    <?php endfor; ?>
</form>
<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        $(document).on('click', '.primary', function() {
            $('#save').submit();
        })
    });
</script>